
import { createClient } from '@supabase/supabase-js'

const supabaseUrl = 'postgresql://postgres.ddyjcrubbcytrtoudrlo:LuDxqQCXYsHjc5QS@aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres'
const supabaseKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRkeWpjcnViYmN5dHJ0b3VkcmxvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjcxMzUxMTQsImV4cCI6MjA0MjcxMTExNH0.gPyt4XOyVkkWr2A0iHTRUQSUHBrh4mcnKgpXrGXPpkQeyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRkeWpjcnViYmN5dHJ0b3VkcmxvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjcxMzUxMTQsImV4cCI6MjA0MjcxMTExNH0.gPyt4XOyVkkWr2A0iHTRUQSUHBrh4mcnKgpXrGXPpkQ'
const supabase = createClient(supabaseUrl, supabaseKey)
